GET http://localhost:4000/

###
POST http://localhost:4000/auth/signup

# POST http://localhost:4000/auth/login

###

POST http://localhost:4000/mail/sendmail

###

POST https://nibsssandbackend.innovantics.com/api/v1/auth/password/reset
Content-Type: application/json

{
    "email": "thevetdoctor@gmail.com",
    "type": "admin"
}

###
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
    "username" : "oba",
    "email" : "oba@mollo.com",
    "password": "pass"
}

###
POST http://ip172-18-0-50-c8qq2dfnjsv000c9nce0-5000.direct.labs.play-with-docker.com/auth/login
Content-Type: application/json

{
    "email": "thevetdoctor@gmail.com",
    "password": "admin"
}

###
POST http://localhost:5000/auth/signup
# POST http://ip172-18-0-50-c8qq2dfnjsv000c9nce0-5000.direct.labs.play-with-docker.com/auth/signup
Content-Type: application/json

{
    "email": "thevetdoctor@gmail.com",
    "password": "admin",
    "username": "admin"
}

###
# GET http://ip172-18-0-50-c8qq2dfnjsv000c9nce0-5000.direct.labs.play-with-docker.com/groups
POST http://localhost:5000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzZjNGRlODUtZjZlMi00NzdlLTkwZWUtZWFjZTk3MDRmMDgxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoidGhldmV0ZG9jdG9yQGdtYWlsLmNvbSIsInBhc3N3b3JkIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiYmlvIjpudWxsLCJsb2NhdGlvbiI6bnVsbCwiZG9iIjpudWxsLCJtb2JpbGUiOm51bGwsInZlcmlmaWVkIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMy0xOVQwOTozODowMy4zMzRaIiwidXBkYXRlZEF0IjoiMjAyMi0wMy0xOVQwOTozODowMy4zMzRaIn0sImlhdCI6MTY0NzY4NjAxOX0.H_IiTRK47enIqRqBRRBQrtpHgzSf0ndDelTiWKdJ-JQ

{
    "description": "admin",
    "name": "admin"
}

###
# GET http://ip172-18-0-50-c8qq2dfnjsv000c9nce0-5000.direct.labs.play-with-docker.com/groups
GET http://localhost:5000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzZjNGRlODUtZjZlMi00NzdlLTkwZWUtZWFjZTk3MDRmMDgxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoidGhldmV0ZG9jdG9yQGdtYWlsLmNvbSIsInBhc3N3b3JkIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiYmlvIjpudWxsLCJsb2NhdGlvbiI6bnVsbCwiZG9iIjpudWxsLCJtb2JpbGUiOm51bGwsInZlcmlmaWVkIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMy0xOVQwOTozODowMy4zMzRaIiwidXBkYXRlZEF0IjoiMjAyMi0wMy0xOVQwOTozODowMy4zMzRaIn0sImlhdCI6MTY0NzY4NjAxOX0.H_IiTRK47enIqRqBRRBQrtpHgzSf0ndDelTiWKdJ-JQ

###
# GET http://ip172-18-0-50-c8qq2dfnjsv000c9nce0-5000.direct.labs.play-with-docker.com/groups
GET http://localhost:5000/members/69a31570-bb0e-427c-9e8d-b6672494d383
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzZjNGRlODUtZjZlMi00NzdlLTkwZWUtZWFjZTk3MDRmMDgxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoidGhldmV0ZG9jdG9yQGdtYWlsLmNvbSIsInBhc3N3b3JkIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiYmlvIjpudWxsLCJsb2NhdGlvbiI6bnVsbCwiZG9iIjpudWxsLCJtb2JpbGUiOm51bGwsInZlcmlmaWVkIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMi0wMy0xOVQwOTozODowMy4zMzRaIiwidXBkYXRlZEF0IjoiMjAyMi0wMy0xOVQwOTozODowMy4zMzRaIn0sImlhdCI6MTY0NzY4NjAxOX0.H_IiTRK47enIqRqBRRBQrtpHgzSf0ndDelTiWKdJ-JQ